config/routes.rb
SgaGrants::Application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  resources :fundraising_histories

  constraints host: APP_CONFIG["survey_host"] do
    get '/', to: "organizations#survey", as: "survey_root"
  end

  get "welcome/index", as: "welcome"

  resources :comments

  resources :organizations do
		get 'survey', on: :collection 
		post 'create_survey', on: :collection
    get 'survey_show', on: :member
    get 'names', on: :collection
	end

  get 'help', to: 'applications#help', as: "help"

  resources :applications do
    get 'new/:organization_id', to: 'applications#new', as: 'organization_id', on: :collection
    resources :steps, controller: "applications/steps"
    get 'verify', on: :member
    put 'governor_update', on: :member
    get 'finance_report', on: :collection
  end

  resources :users, only: [:update, :show, :edit]

  root to: "welcome#index"#, constraints: { host: APP_CONFIG["sga_grants_host"] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :store_location
  before_filter :ensure_signup_completion

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, error: exception.message
  end

  def store_location
    if !(request.fullpath =~ /users/) && !request.xhr?
      session[:previous_url] = request.fullpath
    end
  end

  def access_denied(exception)
    redirect_to root_url
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def ensure_signup_completion
    unless !user_signed_in? || current_user.completed_signup? || (["users", "cas_sessions"].include?(controller_name))
      redirect_to edit_user_path(current_user), flash: {info: t('users.fill_in_info') }
    end
  end

  def notify_incomplete_apps
    if user_signed_in? && current_user.applications.incomplete.any?
      flash.now[:warning] = t('applications.incomplete_app')
    end
  end
end

app/controllers/applications/steps_controller.rb
class Applications::StepsController < ApplicationController
  include Wicked::Wizard
  steps :event, :hotel, :transportation, :expenditures, :fundraising_history

  def show
    @application = Application.find(params[:application_id])
    return redirect_to @application if @application.complete?
    @application.build_event unless @application.event
    @application.event.build_transportation unless @application.event.transportation
    @application.event.build_hotel unless @application.event.hotel
    @application.expenditures.build
    render_wizard
  end

  def update
    @application = Application.find(params[:application_id])
    if (step == :fundraising_history) && (!@application.complete?)
      params[:application][:complete] = true
      session[:app_id] = nil
      deliver_emails
    end
    @application.update_attributes(params[:application])
    render_wizard @application
  end

  private

  def deliver_emails
    access_token = ApiKey.create!.access_token
    people_to_update = [@application.applicant]
    @application.organization.organization_leaders.each{|ol| people_to_update << ol }
    people_to_update.each { |u| ApplicationMailer.application_created(u, @application, access_token).deliver }
  end

  def redirect_to_finish_wizard(options = nil)
    redirect_to application_path(@application), notice: "Thank you for applying. A governor will update you with your date of vote soon."
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :validate_access_token, only: :verify
  before_filter :notify_incomplete_apps

  # GET /applications
  # GET /applications.json
  def index
    authorize! :index, Application
    @statuses = %w{pending archived incomplete}
    respond_to do |format|
      format.html {}
      format.json { render json: ApplicationsDatatable.new(view_context) }
    end
  end

  def help
  end

  def finance_report
    authorize! :finance_report, Application
    @total_grant_capacity = Setting.find_by_property("total_sga_funds").try(:value).try(:to_i)
    if @total_grant_capacity.nil?
      return redirect_to root_path, flash: {error: t('errors.grant_cap_not_set')}
    end
    @applications_final_amount_sum = Application.final_amount_sum

    @remaining_funds = @total_grant_capacity - @applications_final_amount_sum
    @number_at_five_hundred = (@total_grant_capacity / 500).to_i
    @amount_can_give = @total_grant_capacity / @number_at_five_hundred
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.include_all_associations.find(params[:id])
    authorize! :show, @application
    @organization = @application.organization
    respond_to do |format|
      format.html { notify_unverified! unless @application.verified? }
      format.json { render json: @application }
    end
  end

  def new
    return redirect_to organizations_path unless params[:organization_id]
    authorize! :create, Application
    @application = Application.new
    @application.organization = Organization.find(params[:organization_id])
    return invalid_organization!(@application.organization) unless @application.organization.valid?
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  def verify
    @application = Application.find(params[:id])
    @organization_leader = @application.organization.organization_leaders.find(params[:org_leader_id])
    @application.update_attributes(verified: true, verified_by: @organization_leader)
    redirect_to root_path, flash: {success: t('application.verified') }
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
    authorize! :update, @application
    @application.build_event unless @application.event
    @application.event.build_transportation unless @application.event.transportation
    @application.event.build_hotel unless @application.event.hotel
    @application.expenditures.build
  end

  def governor_update
    @application = Application.find(params[:id])
    authorize! :governor_update, @application
    respond_to do |format|
      if @application.update_and_notify(params[:application])
        format.html { redirect_to application_path(@application) }
        format.json { render json: view_context.app_updated_response(@application) }
      else
        format.html {redirect_to application_path(@application), alert: "An error occurred!"}
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = find_or_create_from_session
    @application.applicant = current_user

    authorize! :create, Application
    respond_to do |format|
      if @application.save
        format.html do
          session[:app_id] = @application.id
          redirect_to application_steps_path(application_id: @application.id)
        end
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])
    authorize! :update, @application
    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to application_steps_path(application_id: @application.id) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy
    authorize! :destroy, Application
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private

  def find_or_create_from_session
    if session[:app_id]
      application = Application.find(session[:app_id].to_i)
      application.assign_attributes(params[:application])
      application
    else
      Application.new(params[:application])
    end
  end

  def invalid_organization!(org)
    message = {info: t('organizations.invalid', org_name: org.name.possessive)}
    redirect_to edit_organization_path(org), flash: message
  end

  def notify_unverified!
    message_for = can?(:view_all, Application) ? 'member' : 'applicant'
    flash.now[:info] =  t("applications.unverified_app_#{message_for}")
  end

  def active_tab
    locations_in_url = @statuses.map{|s| request.fullpath.rindex(s) || 0 }
    return @statuses[0] if locations_in_url.all? {|l| l == 0 }
    index_of_last_status_param = locations_in_url.rindex(locations_in_url.max)
    @statuses[index_of_last_status_param]
  end

  def validate_access_token
    api_key = ApiKey.find_by_access_token(params[:access_token])
    redirect_to root_path, flash: {alert: t('errors.invalid_access_token')} unless api_key
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def formatted_event_fields(event)
    fields = {
      place_of_event: event.place_of_event.try(:titleize),
      number_attending: event.number_attending,
      start_date: event.start_date.try(:to_s, :long),
      end_date: event.end_date.try(:to_s, :long)
    }
    hash_to_list_items(fields)
  end

  def app_updated_response(application)
    { 
      error: false,
      response: "Updated",
      partial: formatted_application_fields(application)
    }
  end

  def number_of_rooms_description(hotel)
    "#{hotel.try(:number_of_rooms)} rooms, #{number_to_currency(hotel.try(:cost_per_room))} per room"
  end

  def formatted_hotel_fields(hotel)
    fields = {
      name: hotel.name.try(:titleize),
      total_cost: number_to_currency(hotel.total_cost),
      cost_per_room: number_to_currency(hotel.cost_per_room),
      number_of_rooms: hotel.number_of_rooms,
      people_per_room: hotel.people_per_room,
      city: hotel.city.try(:titleize),
      state: hotel.state.try(:titleize),
      phone: hotel.phone
    }
    fields[:additional_info] = hotel.additional_info unless hotel.additional_info.empty?
    hash_to_list_items(fields)
  end

  def formatted_transportation_fields(transport)
    fields = {
      type: transport.transportation_type.name,
      company: transport.company_name.titleize,
      cost: number_to_currency(transport.cost),
      website: transport.website,
      phone: transport.phone,
    }
    fields[:additional_info] = transport.additional_info unless transport.additional_info.empty?
    hash_to_list_items(fields)
  end

  def formatted_applicant_fields(applicant)
    {
      applicant_name: applicant.try(:fullname),
      applicant_email: (mail_to(applicant.email) if applicant.present?)
    }
  end

  def meeting_time_fields(f)
    style = (f.object.more_often_than_biweekly? ? "display:none;" : "")
    required = (f.object.more_often_than_biweekly? ? false : true)
    week_days = Time::DAYS_INTO_WEEK.keys.map { |d| d.to_s.titleize }
    [
      f.input(:meeting_day_of_week, prompt: "Day of Week", collection: week_days, required: required, style: style),
      f.input(:meeting_time, as: :timepicker, style: style, required: required)
    ].join('').html_safe
  end

  def formatted_application_fields(app)
    fields = {
      amount_requested: number_to_currency(app.amt_requested),
      amount_awarded: number_to_currency(app.final_amount) || content_tag(:em, "Pending"),
      funds_needed_by: app.funds_needed_by.try(:to_s, :long),
      date_of_vote: (app.date_of_vote.try(:to_s, :long) || content_tag(:em, "Unassigned")),
      vote_result: app.vote_result.titleize,
      reason_for_funds: app.reason_for_funds,
      impact_on_university: app.impact_on_univ,
      additional_info: app.additional_info,
      applied_on: app.created_at.to_date.try(:to_s, :long),
      last_updated: app.updated_at.try(:strftime, "%B %e, %Y at %l:%M %p")
    }
    fields.merge!(formatted_applicant_fields(app.applicant))
    verified_by = app.verified_by ? "#{app.verified_by.try(:title).try(:titleize)} #{app.verified_by.try(:fullname)}" : "Unverified"
    fields[:verified_by] = verified_by
    hash_to_list_items(fields)
  end

  def hash_to_list_items(items)
    haml_tag :table, class: "table table-striped" do
      items.each do |key, value|
        haml_tag :tr do
          haml_tag :td, key.to_s.titleize, class: "row-title"
          haml_tag :td, value
        end
      end
    end
  end

  def link_to_add(type, open, container_selector, destroy_selector)
    phrase_to_use = (open ? 'Remove ' : 'Add ') + type.to_s.titleize
    haml_tag :div, class: "add-one-association" do
      haml_tag :span, class: "add-one-wrap" do
        haml_tag :h4, "Would you like to add #{phrase_to_use.downcase} information?", class: "question", style: (open ? 'display:none;' : '')
        haml_tag :a, phrase_to_use, href: "#", id: "add_#{type.to_s}", class: "slider_button btn btn-default #{'open btn-danger' if open}", data: {name: type.to_s.titleize, container: container_selector, destroy: destroy_selector}
      end
    end
  end

  def get_date_string(value)
    (value || DateTime.now).to_date.to_s
  end

  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
end

app/views/applications/_form.html.haml
= render partial: "applications/steps/head", locals: {current: :application}
.content
	= simple_form_for @application, :html => { :class => 'form-horizontal fix_long_textareas grant_app'} do |f|
		= f.input :organization_id, as: :hidden
		= f.input :funds_needed_by, order: [:month, :day, :year]
		= f.input :reason_for_funds, placeholder: "How will an SGA grant benefit your organization?", input_html: {rows: 1}, required: true
		= f.input :impact_on_univ, :label => "Impact on WVU", placeholder: "How will this grant improve WVU?", input_html: {rows: 1}, required: true
		= f.input :additional_info, placeholder: "Anything else?", input_html: {rows: 1}

		.well.text-right.push40down
			= f.submit "Next", :class => "submit-button btn btn-primary"

app/views/applications/_gov_update.html.haml
#gov_update.modal.fade
  .modal-dialog
    = simple_form_for @application, :url => governor_update_application_path(@application, format: :json), :method => :put, :remote => true, :html => {:id => "gov_form", :class => 'form-horizontal fix_long_textareas grant_app'} do |f|
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4.modal-title Governor Actions
        .modal-body
          - if @application.requires_date_of_vote?
            = f.input :date_of_vote, order: [:month, :day, :year], required: true
          - if @application.requires_vote_result?
            = f.input :vote_result, collection: [["Approved", "approved"], ["Denied", "denied"]], include_blank: "Select the vote result"
            .div.final_amt_contain{:style=>"display:none;"}
              = f.input :final_amount, as: :currency
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          = f.submit "Submit", :class => "btn btn-primary"

app/views/applications/edit.html.haml
= render :partial => 'form'

app/views/applications/finance_report.html.haml
.page-header
  %h2 Finance Report
.row.white.jumbotron
  %h3.text-center= t('application.funding_remaining', remaining_funds: @remaining_funds)

  %p.text-center.push40down
    %span.finance_text You can give a total of 
    %input.number_of_grants.form-control{type: "number", value: @number_at_five_hundred, data: {remaining: @remaining_funds}}
    %span.finance_text more grants at the amount of
    %span.amount_can_give_container
      %span.input-group
        %span.input-group-addon $
        %input.amount_can_give.form-control{type: "number", value: @amount_can_give, step: "0.01"}

app/views/applications/help.html.haml
.helpdoc
  .page-header
    %h1 Help
  .container
    %p 
      %i PLEASE READ ALL OF THE FOLLOWING BEFORE CONTINUING. THIS DOCUMENT CONTAINS IMPORTANT DATES AND INFORMATION YOU MUST KNOW BEFORE YOU FILL OUT YOUR GRANT APPLICATION. 

    %p 
      %strong.underline SECTION 6. STUDENT ORGANIZATION GRANT POLICY.
      SGA will set aside a portion of funds to be allocated in the form of grants for the benefit of West Virginia University Student Organizations as stated in Article IV, Section 5 of the Constitution of the Student Government Association. The Student Organization Grants will be subject to the following criteria; 

    %ol
      %li
        %span Student Organizations requesting funding must be recognized as an official West Virginia University Student Organization and must meet any criteria as set forth by the Office of Student Organizations Services, such as but not limited to, completing an annual officer update application and publishing organization meeting dates and times on the University Calendar. 

      %li
        %span Student Organizations requesting funding shall attend at least one SOPAC meeting within a calendar year of receiving SGA student organization grant funds. 

      %li
        %span Student Organizations requesting funding must submit an application, as approved by the Bureau of Finance, at least two weeks before the requested date of funds. 

      %li
        %span Each Student Organization may only receive one approved grant per academic year to fund one organization event, initiative, or project. A grant request must take place within the same academic year in which the funding request is submitted. No funding may be awarded after May 15th. 

      %li 
        %span Grant funding will be allocated in amounts to Student Organizations according to the following guideline structure:
        
        %ol
          %li
            %span Funding requested at $1 to $500. Requested funds must go to the benefit of students at West Virginia University. An organization’s fundraising history will be taken into account in determining the necessity of the grant request. 

          %li
            %span Funding requested at $501 to $1,000. Requested funds must go to the benefit of the whole organization’s student membership. An organization’s fundraising history, community service, and campus activity will be taken into account in determining the necessity of the grant request. 

          %li
            %span Funding requested at $1,001 to $1,500. Requested funds must go to the benefit of students in large across West Virginia University beyond the organization’s general membership. An organization’s fundraising history, community service, campus activity, and local community outreach will be taken into account in determining the necessity of the grant request. 

      %li
        %span Student Organizations requesting funds must comply with any additional information requested by the Bureau of Finance within the scope of the grant request. 

      %li
        %span Student Organizations requesting funds will be given at least one opportunity to present their request for grant funding to the Student Board of Governors before being voted upon by the same Board. The Bureau of Finance may give a recommendation on the Student Organization’s grant request to the Student Board of Governors during this time. The Student Board of Governors will be responsible for the final decision on approving or denying a Student Organization’s Grant request. 

    %p You will be contacted by a representative of the Student Government Association when your grant application is going to be presented to the Board. The email you use to complete the application will be contacted. 

    %p Please fill out the following application as fully as possible. More information allows the Bureau of Finance to make confident recommendations based on your financial need.

app/views/applications/index.html.haml
.page-header
  %h2 Applications
.container
  %ul.nav.nav-tabs.nav-justified
    - @statuses.each do |status|
      %li{class: "#{'active' if status == @statuses.first}" }
        %a{id: "#{status}_tab", href: "##{status}", data: {toggle: "tab"}}= status.titleize
  .tab-content
    #pending.tab-pane.fade.in.active
      %table#pending_table.table.table-striped.table-hover{data: {url: applications_path(format: :json), tab: "#pending_tab"}}
        %thead
          %tr
            %th{"data-dynatable-sorts" => "#{Organization.table_name}.name"} Organization
            %th{"data-dynatable-sorts" => "amt_requested", "data-dynatable-no-sort" => "true"} Amount Requested
            %th.hidden-xs{"data-dynatable-sorts" => "funds_needed_by"} Needed By
            %th{"data-dynatable-sorts" => "date_of_vote"} Date of Vote
            %th.hidden-xs{"data-dynatable-sorts" => "#{Application.table_name}.created_at"} Created
        %tbody
    #archived.tab-pane.fade
      %table#archived_table.table.table-striped.table-hover{data: {url: applications_path(type: :archived, format: :json), tab: "#archived_tab"}}
        %thead
          %tr
            %th{"data-dynatable-sorts" => "#{Organization.table_name}.name"} Organization
            %th.hidden-xs{"data-dynatable-sorts" => "amt_requested", "data-dynatable-no-sort" => "true"} Amount Requested
            %th.hidden-xs{"data-dynatable-sorts" => "date_of_vote"} Date of Vote
            %th.hidden-xs{"data-dynatable-sorts" => "final_amount"} Approved Amount
            %th{"data-dynatable-sorts" => "vote_result"} Vote Result
            %th{"data-dynatable-sorts" => "#{Application.table_name}.created_at"} Created
        %tbody
    #incomplete.tab-pane.fade
      %table#incomplete_table.table.table-striped.table-hover{data: {url: applications_path(type: :incomplete, format: :json), tab: "#incomplete_tab"}}
        %thead
          %tr
            %th{"data-dynatable-sorts" => "#{Organization.table_name}.name"} Organization
            %th.hidden-xs{"data-dynatable-sorts" => "amt_requested", "data-dynatable-no-sort" => "true"} Amount Requested
            %th{"data-dynatable-sorts" => "#{Application.table_name}.created_at"} Created
            %th{"data-dynatable-no-sort" => "true"} Actions
        %tbody

app/views/applications/new.html.haml
= render :partial => 'form'

app/views/applications/show.html.haml
.app-show
  - if @application.requires_governor_attention? && (can? :governor_update, @application) && @application.complete
    .alert.alert-info.gov-update-alert
      %p= link_to "Update", "#gov_update", class: "btn btn-white pull-right", data: {toggle: "modal"}
      %h4= current_user.try(:fname) + ","
      %p= @application.governor_message
  .page-header
    %h3= @application.organization.name
  .row
    .container
      %ul.nav.nav-tabs.nav-justified
        %li.active
          %a{href: "#application", data: {toggle: "tab"}} Application
        %li.dropdown
          %a#orgs_tab_link.dropdown-toggle{href: "#", data: {toggle: "dropdown"}}
            %span Organization
            %b.caret
          %ul.dropdown-menu{role: "menu", aria: {labelledby: "orgs_tab_link"}}
            %li
              %a{href: "#basic", tabindex: "-1", data: {toggle: "tab"}} Basic Info
            %li
              %a{href: "#leadership", tabindex: "-1", data: {toggle: "tab"}} Leadership
            %li
              %a{href: "#financial", tabindex: "-1", data: {toggle: "tab"}} Fundraising History
            - if can? :view_comments, Organization
              %li
                %a{href: "#comments", tabindex: "-1", data: {toggle: "tab"}} Comments
        %li
          %a{href: "#event", data: {toggle: "tab"}} Event
        - if @application.event && @application.event.transportation
          %li
            %a{href: "#transportation", data: {toggle: "tab"}} Transportation
        - if @application.event && @application.event.hotel
          %li
            %a{href: "#hotel", data: {toggle: "tab"}} Hotel
        %li
          %a{href: "#expenditures", data: {toggle: "tab"}} Expenditures
      .tab-content
        #application.tab-pane.fade.in.active
          - formatted_application_fields(@application)
        = render partial: "organizations/tab_content", locals: {active: false}
        #event.tab-pane.fade
          - formatted_event_fields(@application.event) if @application.event
        #transportation.tab-pane.fade
          - formatted_transportation_fields(@application.event.transportation) if @application.event && @application.event.transportation
        #hotel.tab-pane.fade
          - formatted_hotel_fields(@application.event.hotel) if @application.event && @application.event.hotel
        #expenditures.tab-pane.fade
          %table.table.table-striped
            %thead
              %tr
                %th Type
                %th Cost
                %th Description
            %tbody
              - @application.expenditures.each do |e|
                %tr
                  %td= e.expenditure_type.try(:name)
                  %td= number_to_currency(e.try(:cost))
                  %td= e.try(:description)
              - if @application.event && @application.event.transportation
                %tr
                  %td= "Transportation"
                  %td= number_to_currency(@application.event.transportation.cost)
                  %td= @application.event.transportation.company_name.titleize
              - if @application.event && @application.event.hotel
                %tr
                  %td= "Hotel"
                  %td= number_to_currency(@application.event.hotel.total_cost)
                  %td= number_of_rooms_description(@application.event.hotel)
= render partial: "gov_update" if @application.requires_governor_attention? && (can? :governor_update, @application)