config/routes.rb
SgaGrants::Application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  resources :fundraising_histories

  constraints host: APP_CONFIG["survey_host"] do
    get '/', to: "organizations#survey", as: "survey_root"
  end

  get "welcome/index", as: "welcome"

  resources :comments

  resources :organizations do
		get 'survey', on: :collection 
		post 'create_survey', on: :collection
    get 'survey_show', on: :member
    get 'names', on: :collection
	end

  get 'help', to: 'applications#help', as: "help"

  resources :applications do
    get 'new/:organization_id', to: 'applications#new', as: 'organization_id', on: :collection
    resources :steps, controller: "applications/steps"
    get 'verify', on: :member
    put 'governor_update', on: :member
    get 'finance_report', on: :collection
  end

  resources :users, only: [:update, :show, :edit]

  root to: "welcome#index"#, constraints: { host: APP_CONFIG["sga_grants_host"] }

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :cas_authenticatable

  # In order or permission!
  ROLES = %w{user org_leader sga_member treasurer admin}

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :role, :fname, :lname

  has_many :organization_users
  has_many :organizations, :through => :organization_users
  has_many :applications, :foreign_key => :applicant_id

  has_many :updated_organizations, :class_name => "Organization", :foreign_key => :updated_by

  before_save :set_defaults

	validates :fname, presence: true, :on => :update
  validates :lname, presence: true, :on => :update
  validates :email, presence: true, email_format: { message: "Invalid Email Address" }, :on => :update

  def role?(role)
    self.role.to_sym == role
  end

  def completed_signup?
    (self.email.nil? || self.fname.nil? || self.lname.nil?) ? false : true
  end

  def set_defaults
    self.role = "user" if self.role.nil?
    self.email ||= "#{self.username}@mix.wvu.edu"
  end

  def fullname
    "#{self.fname} #{self.lname}".try(:titleize)
  end

  def role_greater_than_or_equal_to?(role)
    self.role ? (ROLES.index(self.role) >= ROLES.index(role.to_s)) : false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
    authorize! :show, @user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    # If we're missing info, load it from WVU's public info
    if @user.fname.nil? || @user.lname.nil? || @user.email.nil?
      url = "#{APP_CONFIG["user_lookup_service"]}/#{@user.username}"
      response = HTTParty.get(url, headers: {"Accept" => "application/json"})
      @remote_user_data = response.parsed_response
      @user.fname = @remote_user_data["firstName"] if @user.fname.nil?
      @user.lname = @remote_user_data["lastName"] if @user.lname.nil?
      @user.email = @remote_user_data["email"] if @user.email.nil?
      @user.save
    end
    authorize! :update, @user
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    authorize! :update, @user
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: t('users.updated') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :fname, :label => "First Name", :required => true, :as => (@user.fname.nil? ? :string : :hidden)
  = f.input :lname, :label => "Last Name", :required => true, :as => (@user.lname.nil? ? :string : :hidden)
  = f.input :email, :as => :email, :required => true
  - if f.object.role_greater_than_or_equal_to?(:admin) || Rails.env.development?
    = f.input :role, :collection => User::ROLES, :required => true, :label_method => :titleize
  .well.row.push40down
    = f.button :submit, :class => 'btn btn-primary pull-right'
    - if f.object.completed_signup?
      = link_to "Cancel", user_path(@user), :class => 'btn btn-default'

app/views/users/edit.html.haml
.page-header
  %h1= (@user.fname.nil? || @user.lname.nil?) ? @user.username : @user.fullname
.content
  = render :partial => "form"

app/views/users/show.html.haml
.page-header
  %h1= @user.fullname

.info-container
  %dl.dl-horizontal
    %dt Name:
    %dd= @user.fullname
    %dt Email:
    %dd= @user.email
    %dt MIX Username:
    %dd= @user.username
    - if @user.role_greater_than_or_equal_to?(User::ROLES[1])
      %dt Role:
      %dd= @user.role.titleize

.well.text-right.push40down
  = link_to "Edit", edit_user_path(@user), :class => 'btn btn-primary'