config/routes.rb
SgaGrants::Application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  resources :fundraising_histories

  constraints host: APP_CONFIG["survey_host"] do
    get '/', to: "organizations#survey", as: "survey_root"
  end

  get "welcome/index", as: "welcome"

  resources :comments

  resources :organizations do
		get 'survey', on: :collection 
		post 'create_survey', on: :collection
    get 'survey_show', on: :member
    get 'names', on: :collection
	end

  get 'help', to: 'applications#help', as: "help"

  resources :applications do
    get 'new/:organization_id', to: 'applications#new', as: 'organization_id', on: :collection
    resources :steps, controller: "applications/steps"
    get 'verify', on: :member
    put 'governor_update', on: :member
    get 'finance_report', on: :collection
  end

  resources :users, only: [:update, :show, :edit]

  root to: "welcome#index"#, constraints: { host: APP_CONFIG["sga_grants_host"] }

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  attr_accessible :description, :category_ids, :primary_category_id, :website, :meeting_day_of_week,
    :meeting_frequency, :meeting_time, :name, :number_of_members, :purpose, :updated_by,
    :fundraising_histories_attributes, :organization_leaders_attributes
  has_many :applications

  belongs_to :updated_by, class_name: "User", :foreign_key => :updated_by

  has_many :category_organizations
  has_many :categories, :through => :category_organizations

  has_many :active_admin_comments, as: :resource
  
  belongs_to :primary_category, :class_name => "Category", :foreign_key => :primary_category_id

  has_many :organization_users
  has_many :organization_leaders

  has_many :users, :through => :organization_users
  has_many :fundraising_histories

  accepts_nested_attributes_for :fundraising_histories, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :organization_leaders, reject_if: :all_blank, allow_destroy: true

  # Define fields that don't need to be filled to create an application without updating org
  # ex. [:number_of_members, :purpose]
  APPLICATION_OPTIONAL_FIELDS = []
  MEETING_FREQUENCIES = {
    0 => "Weekly",
    1 => "Bi-Weekly",
    2 => "Monthly",
    3 => "Semester",
    4 => "Yearly"
  }


  def self.search query
    where("lower(#{Organization.table_name}.name) like ?", "%#{query.downcase}%")
  end

  def self.grouped_by_category
    order("#{Organization.table_name}.name ASC").group_by{|o| o.primary_category.name}.sort
  end

  def self.include_categories_and_leaders
    joins(:categories).includes(:categories, :organization_leaders, :primary_category)
  end

  def category_name
    self.category.name
  end

  def word_meeting_frequency
    MEETING_FREQUENCIES[self.meeting_frequency]
  end

  validates :description, presence: true
  validates :meeting_day_of_week, presence: true
  validates :meeting_frequency, presence: true
  validates :meeting_time, presence: true
  validates :name, presence: true
  validates :number_of_members, presence: true
  validates :number_of_members, numericality: { only_integer: true, greater_than: 0 }
  validates :purpose, presence: true
  validates :primary_category, presence: true
  validates :categories, length: {minimum: 1, message: "You must select at least one category."}

  before_validation :ensure_primary_cat_in_categories

  def ensure_primary_cat_in_categories
    return unless primary_category

    unless categories.include? primary_category
      self.categories << primary_category
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :cas_authenticatable

  # In order or permission!
  ROLES = %w{user org_leader sga_member treasurer admin}

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :role, :fname, :lname

  has_many :organization_users
  has_many :organizations, :through => :organization_users
  has_many :applications, :foreign_key => :applicant_id

  has_many :updated_organizations, :class_name => "Organization", :foreign_key => :updated_by

  before_save :set_defaults

	validates :fname, presence: true, :on => :update
  validates :lname, presence: true, :on => :update
  validates :email, presence: true, email_format: { message: "Invalid Email Address" }, :on => :update

  def role?(role)
    self.role.to_sym == role
  end

  def completed_signup?
    (self.email.nil? || self.fname.nil? || self.lname.nil?) ? false : true
  end

  def set_defaults
    self.role = "user" if self.role.nil?
    self.email ||= "#{self.username}@mix.wvu.edu"
  end

  def fullname
    "#{self.fname} #{self.lname}".try(:titleize)
  end

  def role_greater_than_or_equal_to?(role)
    self.role ? (ROLES.index(self.role) >= ROLES.index(role.to_s)) : false
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index, :names]
  before_filter :notify_incomplete_apps
  before_filter :ensure_category_selected!, only: :create_survey

  def index
    authorize! :index, Organization
    @organizations = Organization.joins(:primary_category).includes(:primary_category)
    @organizations = @organizations.search(params[:search]) if params[:search]
    @organizations = @organizations.grouped_by_category
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @organizations }
    end
  end

  def names
    @organization_names = Organization.pluck(:name)
    render json: @organization_names
  end

  def survey
    @categories = Category.joins(:organizations).includes(:organizations)
    render layout: "university"
  end

  def survey_show
    @organization = Organization.include_categories_and_leaders.find(params[:id])
    render layout: false
  end

  def create_survey
    @organizations = Organization.includes(:organization_leaders).find(params[:category][:organization_ids])
    @organizations.each do |org|
      org.organization_leaders.each do |ol|
        OrganizationMailer.survey_submitted(org, ol, current_user).deliver
      end
    end
    message = t 'organizations.interest_notification', names: @organizations.map(&:name).join(", ")
    redirect_to survey_root_path, notice: message
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization = Organization.include_categories_and_leaders
                                .includes(:fundraising_histories)
                                .find(params[:id])
                                
    authorize! :show, @organization
    respond_to do |format|
      format.html {}
      format.js
      format.json { render json: @organization }
    end
  end

  # GET /organizations/new
  # GET /organizations/new.json
  def new
    authorize! :create, Organization
    @organization = Organization.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organization }
    end
  end

  # GET /organizations/1/edit
  def edit
    @organization = Organization.find(params[:id])
    session[:return_to] ||= request.referer
    # @organization.fundraising_histories.build
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(params[:organization])
    authorize! :create, Organization
    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: t('organizations.created') }
        format.json { render json: @organization, status: :created, location: @organization }
      else
        format.html { render action: "new" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organizations/1
  # PUT /organizations/1.json
  def update
    @organization = Organization.find(params[:id])
    authorize! :update, Organization
    params[:organization][:updated_by] = current_user
    respond_to do |format|
      if @organization.update_attributes(params[:organization])
        format.html { redirect_to @organization, notice: t('organizations.updated', name: @organization.name.possessive ) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization = Organization.find(params[:id])
    @organization.destroy
    authorize! :destroy, Organization
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private

  def ensure_category_selected!
    if params[:category].nil?
      redirect_to survey_root_path, alert: t('organizations.must_select_one')
    end
  end
end

app/views/organizations/_category.html.haml
- category_name ||= "Uncategorized"
.category{:id => category_name.parameterize.underscore, :class => "#{params[:search] ? "col-xs-12" : "col-xs-12 col-sm-6 col-md-4 col-lg-3"}"}
  .list-group
    %span.divider.active.list-group-item
      %h4= category_name
    - organizations.each do |organization|
      = link_to organization.name, organization_path(organization), class: "list-group-item organization_link", data: {push: true}

app/views/organizations/_form.html.haml
= simple_form_for @organization, :html => { :class => 'form-horizontal fix_long_textareas' } do |f|
	= f.input :name, placeholder: "Organization name" if f.object.new_record?
	= f.input :description, placeholder: "Describe your organization", input_html: {rows: 1}
	= f.input :primary_category_id, collection: Category.all.collect{|c| [c.name, c.id]}, prompt: "Primary Category"
	= f.association :categories
	= f.input :meeting_frequency, prompt: "Meeting Frequency", collection: Organization::MEETING_FREQUENCIES.sort.map {|k,v| [v,k]}, required: true, input_html: {data: {:show_and_require_time => "2"}}
	= f.input :meeting_day_of_week, prompt: "Day of Week", collection: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
	= f.input :meeting_time, as: :string, input_html: {type: "time", value: @organization.meeting_time.try(:strftime, "%H:%M")}
	= f.input :purpose, placeholder: "What is your organization's mission?", input_html: {rows: 1}
	= f.input :number_of_members, placeholder: "How many members?"
	%hr
	%h4 Fundraising History
	= render "fundraising_form", org_form: f
	- if can?(:create, Organization)
		%hr
		%h4 Leadership
		#organization_leaders
			= f.simple_fields_for :organization_leaders do |ol|
				= render 'organization_leader_fields', :f => ol
			.links.text-right.col-lg-12
				= link_to_add_association 'Add Leader', f, :organization_leaders, class: "btn btn-default add_leader"
	.well.push40down
		= link_to "Cancel", organizations_path, :class => 'btn btn-default'
		= f.button :submit, :class => 'btn-primary pull-right'

app/views/organizations/_fundraising_form.html.haml
#fundraising_hist_table
  %table.table
    %thead
      %tr
        %th Name
        %th Date
        %th Amount Received
        %th
    %tbody
      - org_form.object.fundraising_histories.order("date asc").each do |f|
        %tr
          %td= f.try(:name)
          %td= f.try(:date)
          %td= number_to_currency(f.try(:amount_received))
          %td
      = org_form.simple_fields_for :fundraising_histories, org_form.object.fundraising_histories.build do |fh|
        - org_form.object.errors.messages.select {|key, value| key.to_s.match(/fundraising_histories/) }.each do |k,v|
          %tr.error-row
            %td{colspan: "4"}
              = k.to_s.try(:gsub, /fundraising_histories./, "").try(:titleize)
              = v.first
        = render 'organizations/fundraising_history_fields', :f => fh
      %tr
        %td{colspan: "4"}= link_to_add_association 'Add Fundraising History', org_form, :fundraising_histories, class: "btn btn-default pull-right", partial: 'organizations/fundraising_history_fields', data: {"association-insertion-node" => "#fundraising_hist_table tr:last", "association-insertion-method" => "before"}

app/views/organizations/_fundraising_history.html.haml
- if @organization.fundraising_histories.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Date
        %th Amount
    %tbody
      - @organization.fundraising_histories.each do |fh|
        %tr
          %td= fh.name
          %td= fh.date.try(:to_formatted_s)
          %td= fh.amount_received
- else
  %p.text-center.muted.push40down There isn't any fundraising history.

app/views/organizations/_fundraising_history_fields.html.haml
%tr.nested-fields
  %td= f.input_field :name, placeholder: "Name"
  %td= f.input_field :date, as: :string, type: "date"
  %td= f.input_field :amount_received, as: :currency, placeholder: "Amount Received"
  %td.remove_assoc
    = link_to_remove_association f, :class => "btn btn-xs btn-default" do
      %i.glyphicon.glyphicon-remove

app/views/organizations/_leadership.html.haml
- if @organization.organization_leaders.size > 0
  .table-responsive.hidden-xs
    %table.table.table-striped
      %thead
        %tr
          %th Name
          %th Position
          %th Email
      %tbody
        - @organization.organization_leaders.each do |l|
          %tr
            %td= l.fullname
            %td= l.title.try(:titleize)
            %td= mail_to l.email, l.email

  .hidden-md.hidden-lg.hidden-sm
    %dl
      - @organization.organization_leaders.each do |l|
        %dt= [l.title.try(:titleize), l.fullname].compact.join(' ')
        %dd= mail_to l.email, l.email
        %br
- else
  %p.text-center.muted No information

app/views/organizations/_organization_leader_fields.html.haml
.nested-fields.leadership_row
  .col-lg-12
    = f.input :title, label: "Title", placeholder: "Title"
    = f.input :fname, label: "First name", placeholder: "First name"
    = f.input :lname, label: "Last name", placeholder: "Last name"
    = f.input :email, as: :email, label: "Email address", placeholder: "Email"
    .remove_assoc.text-right
      = link_to_remove_association f, :class => "btn btn-xs btn-default" do
        %i.glyphicon.glyphicon-remove

app/views/organizations/_search.html.haml
- if @organizations.empty?
  %p.text-center.push40down No Results!
- else
  - @organizations.each do |category_name, organizations|
    = render 'category', category_name: category_name, organizations: organizations

app/views/organizations/_survey_info.html.haml
%h3 What is the Fresh Start Survey?
%p= t 'organizations.survey_intro'

%p= t 'organizations.survey_explanation'

app/views/organizations/_tab_content.html.haml
#basic.tab-pane.fade.in{:class => (active ? "active" : "")}
  = render "organizations/basic_info"
#leadership.tab-pane.fade
  = render "organizations/leadership"
#financial.tab-pane.fade
  = render "organizations/fundraising_history"
- if can? :view_comments, Organization
  #comments.tab-pane.fade
    = render "organizations/comments"

app/views/organizations/index.html.haml
.row
  .page-header.orgs-index-head
    .row.orgs-search
      %h1.col-sm-6.hidden-xs Organizations
      .col-sm-6.col-xs-12.search-wrap
        .search-hide
          = form_tag organizations_path(format: :js), method: :get, remote: true, id: "search_form" do 
            .input-group.col-lg-8.col-xs-10.pull-right.search-width
              = search_field_tag(:search, params[:search], {class: "form-control search", placeholder: "Search Organizations...", data: {source: names_organizations_path(format: :json)}})
              %span.input-group-btn
                = submit_tag("Go", class: "btn btn-primary search-button")
  #main_orgs_list
    - if @organizations.size > 0
      .organizations_wrapper.row
        - @organizations.each do |category_name, organizations|
          = render 'category', category_name: category_name, organizations: organizations
    - else
      %p.muted{:style => "text-align:center;"} No organizations!
  #results
- if can?(:create, Organization)
  .row.push40down
    = link_to 'New Organization', new_organization_path, class: "btn btn-primary btn-block"

app/views/organizations/new.html.haml
.page-header
  %h1 New Organization
.content
  = render :partial => 'form'

app/views/organizations/show.html.haml
.page-header
  %h3= @organization.name
.show-wrap
  = render partial: "show"
.well.push40down
  = link_to "Back", organizations_path, :class => 'btn btn-default'
  .pull-right
    = link_to("Edit", edit_organization_path(@organization), :class => 'btn btn-default') if (can? :edit_on_show_page, Organization)
    - if @organization.valid?
      %button.btn.btn-primary{type: "button", data: {toggle: "modal", target: "#help_modal"}} Apply for Grant
    - else
      = link_to "Apply for Grant", organization_id_applications_path(@organization.id), class: "btn btn-primary"

#help_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title Terms and Conditions
      .modal-body
        = render file: "applications/help"
      .modal-footer
        %label.col-xs-6
          = check_box_tag "accept_terms"
          I confirm that I have read and understood the terms and conditions.
        .text-right.col-xs-6
          = link_to "Proceed", organization_id_applications_path(@organization.id), class: "btn btn-primary disabled", role: "button", id: "proceed_with_application", data: {"skip-pjax" => true}

app/views/organizations/survey.html.haml
.content
  .show-phone= render "organizations/survey_info"
  .category-form.sixteen.columns.alpha
    = form_for :organizations, url: create_survey_organizations_path, method: :post do |f|
      .section-container.accordion{"data-section" => "accordion"}
        - @categories.each_with_index do |category, index|
          %section
            %p.title{"data-section-title" => ""}
              %a{href: "#panel1"}= category.name
              %span.arrow-down
            .content.sixteen.columns.alpha{"data-section-content" => ""}
              - if category.organizations.empty?
                %p.text-center.muted= "There aren't any organizations in the #{category.name} category."
              - else
                - remainder = category.organizations.size % 2
                - category.organizations.each_slice((category.organizations.size/2) + remainder).with_index do |organizations_column, index|
                  - alpha_or_omega = index == 0 ? "alpha" : "omega"
                  .eight.columns{class: alpha_or_omega}
                    - organizations_column.each do |o|
                      .org_checkbox
                        = check_box_tag("category[organization_ids][]", value = o.id, false, {class: "survey_check"})
                        %label
                          %a.surveypopup{data: {id: o.id, source: survey_show_organization_path(o)}}= o.name
      = f.submit "Submit Fresh Start Survey", class: "submit_fresh_start"
#modal.reveal-modal.large
  %p Loading...