config/routes.rb
SgaGrants::Application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)

  resources :fundraising_histories

  constraints host: APP_CONFIG["survey_host"] do
    get '/', to: "organizations#survey", as: "survey_root"
  end

  get "welcome/index", as: "welcome"

  resources :comments

  resources :organizations do
		get 'survey', on: :collection 
		post 'create_survey', on: :collection
    get 'survey_show', on: :member
    get 'names', on: :collection
	end

  get 'help', to: 'applications#help', as: "help"

  resources :applications do
    get 'new/:organization_id', to: 'applications#new', as: 'organization_id', on: :collection
    resources :steps, controller: "applications/steps"
    get 'verify', on: :member
    put 'governor_update', on: :member
    get 'finance_report', on: :collection
  end

  resources :users, only: [:update, :show, :edit]

  root to: "welcome#index"#, constraints: { host: APP_CONFIG["sga_grants_host"] }

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %title= content_for?(:title) ? yield(:title) : "SGA Grants"
    = favicon_link_tag
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400,700", :rel => "stylesheet", :type=>"text/css"}
    = stylesheet_link_tag "application", :media => "all"
    = stylesheet_link_tag "print", :media => "print"
    = javascript_include_tag "application"
  %body
    #wrap
      .navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to(root_url, :class => "navbar-brand") do
              %span{:style => "font-weight:700;"} SGA
              Grants
          .collapse.navbar-collapse
            - if user_signed_in?
              %ul.nav.navbar-nav
                %li= link_to "Organizations", organizations_path
                %li= link_to "Applications", applications_path
                - if can?(:finance_report, Application)
                  %li= link_to "Finance Report", finance_report_applications_path
                - if can? :read, ActiveAdmin::Page, :name => "Dashboard"
                  %li= link_to "Admin", admin_root_path, data: {"no-turbolink" => "true"}
            %ul.nav.navbar-nav.pull-right.user-login-dd
              %li.dropdown
                - if user_signed_in?
                  = link_to (current_user.username + content_tag(:b, nil, class: "caret")).html_safe, "#", :class=>"dropdown-toggle", :data => {:toggle => "dropdown"}
                  %ul.dropdown-menu
                    %li= link_to "Profile", user_path(current_user)
                    %li= link_to "Help", help_path
                    %li= link_to "Logout", destroy_user_session_path, :method => :delete
                - else
                  = link_to "Login", new_user_session_path
      = content_for :jumbotron
      .main_content.container
        #content
          = bootstrap_flash
          = yield

    %footer
      .container
        %ul.list-unstyled
          %li
            = link_to "Home", welcome_path
          %li
            = link_to "Organizations", organizations_path
          %li
            %a{href: "http://sga.wvu.edu"} WVU SGA
          %li
            %a{href: "http://sos.wvu.edu"} Student Organization Services
        %p
          %small
            Made by Ray Zane and licensed under the
            %a{href: "https://github.com/rzane/sga_grants/blob/master/COPYING"} GNU General Public License.

app/views/layouts/university.html.haml
!!!
/[if IE 8] <html class="ie8" lang="en">
/ [if gt IE 8]><!
%html{lang: "en"}
  / <![endif]
  %head
    %meta{charset: "iso-8859-1"}/
    %meta{content: "Give a description of your site", name: "description"}/
    %meta{content: "Keywords for your site", name: "keywords"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title Fresh Start Survey | West Virginia University
    = stylesheet_link_tag "survey"
    %link{href: "http://slate.wvu.edu/themes/shared/scss/v4/stylesheets/global-v4.css", rel: "stylesheet"}/
    /[if lt IE 9]
      = javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"
    / The HTML5 Shiv is *required* for IE to recognize the new HTML5 tags
  %body#university
    .wvu-masthead
      .wvu-masthead-container
        %a.wvu-official-logo{href: "http://www.wvu.edu/"} West Virginia University
        %ul
          %li
            %a{href: "http://www.wvu.edu/SiteIndex/"} A-Z Site Index
          %li
            %a{href: "http://beta.campusmap.wvu.edu/"} Campus Map
          %li
            %a{href: "http://employmentservices.hr.wvu.edu/wvu_jobs"} Jobs
          %li
            %a{href: "http://directory.wvu.edu/"} Directory
          %li
            %a{href: "http://www.wvu.edu/"} WVU Home
      / /.masthead-container
    / /.wvu-masthead
    .container
      %header.sixteen.columns
        = bootstrap_flash
        = link_to "Fresh Start Survey", survey_organizations_path, class: "site-logo"
      %main.main.twelve.columns{role: "main"}
        / role="main", etc are ARIA roles, use appropriately: http://goo.gl/P3voj | Include a search in your theme: http://goo.gl/InZM8
        = yield
      / /.main
      %aside.sidebar.four.columns{role: "complementary"}
        .hide-phone= render "organizations/survey_info"
      / /.sidebar
      %footer.footer
        .wvu-contact
          %p
            %strong Student Organization Services
            %br/
            West Virginia University
            %br/
            Mountainlair
            %br/
            PO Box 6444
            %br/
            Morgantown, WV 26506
            %br/
            (304)293-4397
            %br/
            %a{href: "mailto:sos-reservation@mail.wvu.edu"} sos-reservation@mail.wvu.edu
        / /.wvu-contact
        %br.clear/
        .wvu-credits{role: "contentinfo"}
          %ul
            %li
              %a{href: "http://about.wvu.edu/wvu-facts"} Accreditations
            %li
              %a{href: "http://brand.wvu.edu/web_standards"} Web Standards
            %li
              %a{href: "mailto:web_services@mail.wvu.edu"} Questions or Comments?
          %p © 2013 West Virginia University. West Virginia University is an Equal Opportunity/Affirmative Action institution.
        / /.wvu-credits
        .wvu-icons
          %ul.wvu-links
            %li
              %a{href: "http://www.wvuf.org/"} Give
            %li
              %a{href: "http://myaccess.wvu.edu/"} MyAccess
            %li
              %a{href: "http://careerservices.wvu.edu/mountaineertraklogins"} MountaineerTRAK
            %li
              %a{href: "http://emergency.wvu.edu/alert/"} WVU Alert
            %li
              %a{href: "http://wvutoday.wvu.edu"} WVU Today
            %li
              %a{href: "http://mix.wvu.edu/"} MIX
          %ul.wvu-social
            %li
              %a.wvu-facebook{href: "http://www.facebook.com/wvumountaineers"} WVU on Facebook
            %li
              %a.wvu-twitter{href: "https://twitter.com/WestVirginiaU/"} WVU on Twitter
            %li
              %a.wvu-youtube{href: "http://www.youtube.com/westvirginiau"} WVU on YouTube
        / /.wvu-icons
    / /.container
    / Fix IE 8 and below so that media queries get supported
    /[if lt IE 9]
      <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.min.js"></script>
    / begin browser-update.org
    :javascript
      var $buoop = {} 
      $buoop.ol = window.onload; 
      window.onload=function(){ 
         try {if ($buoop.ol) $buoop.ol();}catch (e) {} 
         var e = document.createElement("script"); 
         e.setAttribute("type", "text/javascript"); 
         e.setAttribute("src", "http://browser-update.org/update.js"); 
         document.body.appendChild(e); 
      }
    / end browser-update.org
    = javascript_include_tag "survey"